version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: brain-task-app
    IMAGE_TAG: latest
    REPOSITORY_URI: 304534110140.dkr.ecr.ap-south-1.amazonaws.com/brain-task-app
    K8S_DEPLOYMENT_NAME: brain-tasks-deployment
    K8S_CONTAINER_NAME: brain-tasks
    K8S_NAMESPACE: default  # Change if you use a different namespace

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Ensure EKS config is set
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-cluster-1
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
post_build:
  commands:
    - echo Build completed on `date`
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Updating Kubernetes deployment...
    - kubectl patch serviceaccount default -n $K8S_NAMESPACE -p "{\"imagePullSecrets\":[{\"name\":\"ecr-secret\"}]}"
    - kubectl set image deployment/$K8S_DEPLOYMENT_NAME $K8S_CONTAINER_NAME=$REPOSITORY_URI:$IMAGE_TAG -n $K8S_NAMESPACE
    - kubectl rollout status deployment/$K8S_DEPLOYMENT_NAME -n $K8S_NAMESPACE
    - echo Deployment completed successfully!


artifacts:
  files:
    - '**/*'
